apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: j7sudkiup-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/j7sudkiup-java-quarkus-gitops